FS: 44100
WIN_SIZE: 8192
BLOCKSIZE: 1024
HOP_TIME: 0.04
RMS_THRESHOLD: 1e-4
RMS_ACTIVE_THRESHOLD: 0.003
RMS_MIN: 0.001
RMS_MAX: 0.5
ALPHA: 0.95
SMOOTH_ALPHA: 0.6 
YIN_THRESHOLD: 0.1
BAR_SPAN: 10.0
BAR_WIDTH: 24

TARGET_FREQS:
  E₂: 82.41
  A₂: 110.00
  D₃: 146.83
  G₃: 196.00
  B₃: 246.94
  E₄: 329.63
